#!/bin/bash

function setup()
{
    export STUDIO_TARGET=http://localhost:9999
    source /etc/bash.bashrc
    echo "updated STUDIO_TARGET"
}


function updateNodeJS()
{
    npm install
    npm audit fix
}


function run()
{
    setup
    updateNodeJS
    npm run serve
}


"$@"