#!/bin/bash

function commandHistory()
{
    history
}


function setHistorySize()
{
    newHistorySize=$1
    HISTSIZE=$newHistorySize
}


function unsetVariable()
{
    variableToUnset=$1
    unset $variableToUnset
}


"$@"